const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHEMENT = "NEW_ATTACHEMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

module.exports = { ALERT, REFETCH_CHATS, NEW_ATTACHEMENT, NEW_MESSAGE_ALERT }